import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nature Saviors",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=''>
        <div className=" h-[100vh]  w-[100vw]   relative gradient">
          
        <Navbar />
        </div>
        {children}
        

          
         
      </body>
    </html>
  );
}
